palette="iskald"

## FIRST LINE/ROW: Info & Status
# First param â”€â”Œ
[username]
format = " [$user]($style) at "
show_always = true
style_root = "color_1"
style_user = "color_2"

# Second param
[hostname]
disabled = false
format = "[$hostname]($style) in "
ssh_only = true
style = "color_2"
trim_at = "-"

# Third param
[directory]
style = "color_3"
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "î™›  "

# Fourth param
[sudo]
disabled = false

# Before all the version info (python, nodejs, php, etc.)
[git_status]
ahead = "â‡¡${count}"
behind = "â‡£${count}"
deleted = "x"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
style = "color_4"

# Last param in the first line/row
[cmd_duration]
disabled = false
format = "took [$duration]($style)"
min_time = 1000
style = "color_4"


## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
charging_symbol = "ï–ƒ"
disabled = true
discharging_symbol = "ï–‚"
full_symbol = "ï•¸"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
disabled = false
style = "color_4"
threshold = 15

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
disabled = true
style = "bold yellow"
threshold = 50

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
disabled = true
style = "bold green"
threshold = 80

# Prompt: optional param 1
[time]
disabled = true
format = " ğŸ•™ $time($style)\n"
style = "color_4"
time_format = "%T"

# Prompt: param 2
[character]
error_symbol = " [Ã—](bold color_1)"
success_symbol = " [â¯](bold color_1)"

# SYMBOLS
[status]
disabled = false
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
pipestatus = true
symbol = "ğŸ”´"

[aws]
symbol = "îŒ½ "
style = "color_3"

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "
style = "color_3"

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
symbol = "ï˜ "
style = "bold cambridgeblue"

[golang]
symbol = "î˜§ "
style = "color_3"

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "î‰ "
style = "color_3"

[package]
symbol = "ó°– "
style = "color_4"

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[swift]
symbol = "ï¯£ "


[palettes.iskald]
color_fg = "#F4F4F9"
color_bg = "#000000"
color_0 = "#000000"
color_1 = "#2F4550"
color_2 = "#586F7C"
color_3 = "#B8DBD9"
color_4 = "#F4F4F9"
color_5 = "#2F4550"
color_6 = "#B8DBD9"
color_7 = "#F4F4F9"
color_8 = "#2F4550"
color_9 = "#586F7C"
color_10 = "#B8DBD9"
color_11 = "#F4F4F9"
color_12 = "#586F7C"
color_13 = "#B8DBD9"
color_14 = "#F4F4F9"
color_15 = "#F4F4F9"
